### ISSUE TITLE
Typo on the project's npm page

### ISSUE THREAD

**Issue by ValentineStone** [neo4j-graphql/neo4j-graphql-cli#4]
On the npm page the install command is written as folows:

`npm install -g neo4j-graph-cli`

Where as it should instead be:

`npm install -g neo4j-graphql-cli`

GitHub page has the correct command, where as npm's page got the broken one.
I copy/pasted it and it got me XD

**Comment by johnymontana** [comment]
Fixed by deploying patch release to npm. Thanks for reporting!
